<a href="https://colab.research.google.com/github/alexandrufrunza/Sisteme-integrate/blob/main/Laborator1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Obiective
* Tensori
* Derivate
* Seturi de date
* Regresia lineara
* Metoda gradientului





## Importarea librariilor necesare

In [2]:
import torch 
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

'1.7.0+cu101'

# Generarea unui vector/unei matrici folosind NumPy
**Proces similar cu generarea de vectori si matrici folosind Matlab**

In [5]:
vec_np = np.array([12, 4, -4 ,4])
print(vec_np)

mat_np = np.array([[12, 0, -4], [5, 7, 9]])
print(mat_np)

[12  4 -4  4]
[[12  0 -4]
 [ 5  7  9]]


# Generarea unui tensor folosind PyTorch

In [6]:
vec_torc = torch.tensor([[0, 5, 28, 4], [-3, -6, 8, 2]])
print(vec_torc)

tensor([[ 0,  5, 28,  4],
        [-3, -6,  8,  2]])


# Tipuri de date

In [8]:
int_tensor = torch.tensor([1, 4, 5])
float_tensor = torch.tensor([1., 4., 5.])
print("Tipul de date continute de catre tensori: ", int_tensor.dtype, float_tensor.dtype)
print("Tipul de tensor: ", int_tensor.type(), float_tensor.type())

Tipul de date continute de catre tensori:  torch.int64 torch.float32
Tipul de tensor:  torch.LongTensor torch.FloatTensor


In [9]:
Float_Tensor = torch.FloatTensor([11, 0, 13])
Int_Tensor = torch.tensor([12, 0, 8])
New_Float_Tensor = Int_Tensor.type(torch.FloatTensor)
print("Tipul de date continute de catre tensori: ", Float_Tensor.dtype, Int_Tensor.dtype, New_Float_Tensor.dtype)
print("Tipul de tensor: ", Float_Tensor.type(), Int_Tensor.type(), New_Float_Tensor.type())

Tipul de date continute de catre tensori:  torch.float32 torch.int64 torch.float32
Tipul de tensor:  torch.FloatTensor torch.LongTensor torch.FloatTensor


# Dimensiuni

In [15]:
# Vizualizarea dimensiunilor tensorilor
a = torch.tensor([[54, 32, 56], [4, 6, 4], [23, 4 ,7], [-2, -5, -6]])
print(a.size())
print(a.ndimension())

b = torch.tensor([1, 3, -12, -4])
print(b.size())
print(b.ndimension())

c = torch.tensor(1)
print(c.size())
print(c.ndimension())

# Modificarea dimensiunilor tensorilor
a_34 = a.view(3,4)

torch.Size([4, 3])
2
torch.Size([4])
1
torch.Size([])
0
